export const strings = {
  howToUse: "How to Use This Tool",
  disclaimer: "All searches are executed through Google Search. This project is not affiliated with Google.",
  customizeJobTitles: "Customize Job Titles",
  executeSearch: "Execute Search",
  step1: "1. Add Your Job Titles:",
  step1Details: "Start by adding at least one job title to enable the search functionality. Click the \"Customize Job Titles\" button to begin.",
  step2: "2. Browse Categories:",
  step2Details: "Explore different search categories below, each containing specialized search queries for finding job opportunities.",
  step3: "3. Execute Searches:",
  step3Details: "Click any \"Execute Search\" button to open the search query in a new tab on Google. Each search is optimized for finding specific types of job listings.",
  step4: "4. Customize & Refine:",
  step4Details: "Add or modify job titles anytime to refine your search. All search queries will automatically update with your changes.",
  addNewTitle: "Add new job title...",
  add: "Add",
  suggestedTitles: "Suggested titles:",
  minTitlesRequired: "Add at least one job title to enable searches",
  madeWith: "Made with",
  by: "by",
  allSearchesFrom: "All search queries are courtesy of",
  categories: {
    "Essential Searches": "Essential Searches",
    "Remote Work": "Remote Work",
    "Major Job Platforms": "Major Job Platforms",
    "Tech Industry": "Tech Industry",
    "Finance & Consulting": "Finance & Consulting",
    "Healthcare & Pharma": "Healthcare & Pharma",
    "Creative & Design": "Creative & Design",
    "Alternative Sources": "Alternative Sources"
  },
  searches: {
    "Basic Job Search": "Basic Job Search",
    "Detailed Job Search": "Detailed Job Search",
    "Recent Job Openings": "Recent Job Openings",
    "Remote Jobs": "Remote Jobs",
    "US Remote Jobs": "US Remote Jobs",
    "Greenhouse Jobs": "Greenhouse Jobs",
    "Lever Jobs": "Lever Jobs",
    "Ashby Jobs": "Ashby Jobs",
    "Top Tech Companies": "Top Tech Companies",
    "Tech Startups": "Tech Startups",
    "Web3 & Crypto": "Web3 & Crypto",
    "Big 4 Consulting": "Big 4 Consulting",
    "Top Consulting": "Top Consulting",
    "Investment Banking": "Investment Banking",
    "FinTech": "FinTech",
    "Top Pharma": "Top Pharma",
    "Clinical Research": "Clinical Research",
    "Creative Agencies": "Creative Agencies",
    "UX/UI Design": "UX/UI Design",
    ".CO Domain Jobs": ".CO Domain Jobs",
    ".IO Domain Jobs": ".IO Domain Jobs",
    "Non-Standard Domains": "Non-Standard Domains"
  }
}; 